site: Iqbal Birrul Walidain
url: https://iqbal.page
title: Iqbal.page
description: Personal Blogs

twitter:
  username: iqbalbirrul
  card: summary
  creator: iqbalbirrul
author:
  twitter: iqbalbirrul
  name: iqbalbirrul
  avatar:
  email: iqbalbirrul@gmail.com
  url: https://iqbal.page
permalink: /:year/:month/:title.html

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  - deploy.sh
  - live.sh
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed
  
destination: docs

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

jekyll_admin:
  hidden_links:
    - datafiles
   
Collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:title.html
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
