site: Iqbal
url: https://iqbal.page
title: Iqbal Birrul Walidain
description: Personal Blogs

twitter:
  username: #iqbalbirrul
  card: summary
  creator: #yourusername
author:
  twitter: #yourusername
  name: #yourusername
  avatar:
  email: #youremail
  url: #yoururl
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  - deploy.sh
  - live.sh
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-leaf.gemspec
  - LICENSE.txt
  - README.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed
  
destination: docs

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

jekyll_admin:
  hidden_links:
    - datafiles
   
Collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:title.html
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
